jwt:
  auth:
    secret_key: testkey#secret@12334
    expires_in: '3600'
    app: Spring-Security-App
spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/crowdmarketing?useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&nullCatalogMeansCurrent=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    password: root
  jpa:
    generate-ddl: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: validate
    show-sql: 'false'
server:
  port: ${PORT:8083}
